name: Build Rocky8 base Docker img
run-name: ${{ github.actor }} is attempting to build rocky 8 base docker image 🚀
on: workflow_dispatch
permissions: write-all
jobs:
  build_base8_build-image:
    name: Build base docker image for Rocky8
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
          
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: docker/rocky8/base-build
        push: true
        tags: ghcr.io/${{ github.repository }}/rocky8_base-build:latest
